fily = open('file.txt', 'r')
content = fily.read()
print(f'Содержимое файла: \n {content}')
fily = open('file.txt', 'r')
content = fily.readlines()
print(f' Количество строк в файле - {len(content)}')
fily = open('file.txt', 'r')
content = fily.readlines()
for i in range(len(content)):
    print(f'Количество символов {i + 1} - ой строки {len(content[i])}')
fily = open('file.txt', 'r')
content = fily.read()
content = content.split()
print(f'Общее количество слов - {len(content)}')
fily.close()